---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Pull Docker image
      docker_image:
        name: shrey302/calculator:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: MyCalculator
        image: shrey302/calculator:latest
        state: started
        restart_policy: always

