---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: shrey302/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Check if MyCalculator container already exists
      docker_container:
        name: MyCalculator
        state: absent
    - name: Running container
      shell: docker run -it -d --name MyCalculator shrey302/calculator
